channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - rise
  - statsmodels
  - scikit-learn
  - jupyter_nbextensions_configurator
  - pip:
    - jupyter-contrib-nbextensions
